import { useState } from 'react'
import { useGenerateStore } from '../stores/useGenerateStore'
import { useExecuteStore } from '../stores/useExecuteStore'
import { useFileStore } from '../stores/useFileStore'

/**
 * Build a GUI-enabled standalone script.
 * - Double-click: opens file picker dialog
 * - Drag & drop onto .bat: passes file as argument
 * - CLI: python tool.py --input file.xlsx
 */
function buildToolScript(code: string, summary: string): string {
  // Escape backticks and backslashes for template literal safety
  const safeSummary = summary.replace(/\\/g, '\\\\').replace(/"/g, '\\"')

  return `#!/usr/bin/env python3
"""${safeSummary}

使い方:
    1. ダブルクリック → ファイル選択ダイアログが開きます
    2. ドラッグ＆ドロップ → 同梱の run.bat にExcelをドロップ
    3. コマンドライン → python tool.py --input ファイル.xlsx --output 出力先

Generated by ToolBilder
"""

import argparse
import os
import sys
import tkinter as tk
from tkinter import filedialog, messagebox

def _select_file_gui():
    """GUIでファイル選択ダイアログを表示"""
    root = tk.Tk()
    root.withdraw()
    root.attributes("-topmost", True)
    file_path = filedialog.askopenfilename(
        title="処理するExcelファイルを選択してください",
        filetypes=[("Excel files", "*.xlsx *.xls *.csv"), ("All files", "*.*")],
    )
    root.destroy()
    return file_path

def _show_result(message, is_error=False):
    """処理結果をダイアログで表示"""
    root = tk.Tk()
    root.withdraw()
    root.attributes("-topmost", True)
    if is_error:
        messagebox.showerror("エラー", message)
    else:
        messagebox.showinfo("完了", message)
    root.destroy()

def _setup():
    parser = argparse.ArgumentParser(description="${safeSummary}")
    parser.add_argument("--input", "-i", help="入力Excelファイルのパス")
    parser.add_argument("--output", "-o", help="出力ディレクトリ")
    parser.add_argument("file", nargs="?", help="入力ファイル（ドラッグ＆ドロップ用）")
    args = parser.parse_args()

    # 優先順位: --input > 位置引数 > GUIダイアログ
    input_file = args.input or args.file
    if not input_file:
        input_file = _select_file_gui()
    if not input_file:
        print("ファイルが選択されませんでした。")
        sys.exit(1)

    # 出力先: --output > 入力ファイルと同じディレクトリ
    output_dir = args.output or os.path.dirname(os.path.abspath(input_file))

    os.environ["INPUT_FILE"] = os.path.abspath(input_file)
    os.environ["OUTPUT_DIR"] = output_dir
    return input_file, output_dir

_input_file, _output_dir = _setup()

# ============================================================
# ここから生成されたコード
# ============================================================

${code}
`
}

function buildBatFile(): string {
  return `@echo off
setlocal

set "TOOL_DIR=%~dp0"

where uv >nul 2>&1
if errorlevel 1 (
    echo [Setup] Installing uv ...
    powershell -ExecutionPolicy ByPass -Command "irm https://astral.sh/uv/install.ps1 | iex"
    set "PATH=%USERPROFILE%\\.local\\bin;%PATH%"
)

if not exist "%TOOL_DIR%.venv" (
    echo [Setup] Creating environment ...
    uv venv "%TOOL_DIR%.venv" --quiet
    echo [Setup] Installing dependencies ...
    uv pip install --python "%TOOL_DIR%.venv\\Scripts\\python.exe" pandas openpyxl --quiet
    echo [Setup] Ready.
    echo.
)

if "%~1"=="" (
    uv run --python "%TOOL_DIR%.venv\\Scripts\\python.exe" "%TOOL_DIR%tool.py"
) else (
    uv run --python "%TOOL_DIR%.venv\\Scripts\\python.exe" "%TOOL_DIR%tool.py" --input "%~1"
)

if errorlevel 1 (
    echo.
    echo Error occurred.
)
pause
`
}

function buildReadme(summary: string, steps: string[]): string {
  const stepList = steps.map((s, i) => `${i + 1}. ${s}`).join('\n')
  return `# ツール説明

${summary}

## 使い方

### 方法1: ダブルクリック（一番簡単）
1. run.bat をダブルクリック
2. ファイル選択ダイアログが表示されます
3. 処理するExcelファイルを選択
4. 処理結果が同じフォルダに出力されます

### 方法2: ドラッグ＆ドロップ
1. 処理するExcelファイルを run.bat にドラッグ＆ドロップ
2. 処理結果が同じフォルダに出力されます

## 処理内容
${stepList}

## 必要な環境
- Python 3.10以上
- pip install pandas openpyxl

Generated by ToolBilder
`
}

async function downloadAsZip(code: string, summary: string, steps: string[]) {
  // Build file contents
  const toolPy = buildToolScript(code, summary)
  const runBat = buildBatFile()
  const readme = buildReadme(summary, steps)

  // Use JSZip-like manual ZIP creation is complex,
  // so we use the backend to create the zip
  const response = await fetch('/api/package-tool', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      tool_py: toolPy,
      run_bat: runBat,
      readme: readme,
    }),
  })

  if (!response.ok) {
    // Fallback: download individual files
    downloadFile(toolPy, 'tool.py', 'text/x-python;charset=utf-8')
    downloadFile(runBat, 'run.bat', 'text/plain;charset=utf-8')
    downloadFile(readme, 'README.txt', 'text/plain;charset=utf-8')
    return
  }

  const blob = await response.blob()
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = 'tool.zip'
  a.click()
  URL.revokeObjectURL(url)
}

function downloadFile(content: string, filename: string, type: string) {
  const blob = new Blob([content], { type })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}

export function CodeResult() {
  const { response } = useGenerateStore()
  const { executeResponse, executing, executeError, execute } = useExecuteStore()
  const { uploadResponse } = useFileStore()
  const [copied, setCopied] = useState(false)
  const [showCode, setShowCode] = useState(false)

  if (!response) return null

  const handleCopy = async () => {
    await navigator.clipboard.writeText(response.python_code)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  const handleExecute = () => {
    void execute(response.python_code, uploadResponse?.file_id)
  }

  const handleDownloadTool = () => {
    void downloadAsZip(response.python_code, response.summary, response.steps)
  }

  return (
    <div className="w-full space-y-4">
      <div className="bg-gray-800 border border-gray-700 rounded-lg p-4">
        <h2 className="text-sm font-semibold text-gray-400 uppercase tracking-wider mb-2">
          概要
        </h2>
        <p className="text-gray-100 text-sm">{response.summary}</p>
      </div>

      {response.steps.length > 0 && (
        <div className="bg-gray-800 border border-gray-700 rounded-lg p-4">
          <h2 className="text-sm font-semibold text-gray-400 uppercase tracking-wider mb-3">
            実行ステップ
          </h2>
          <ol className="space-y-1.5 list-decimal list-inside">
            {response.steps.map((step, index) => (
              <li key={index} className="text-gray-200 text-sm">
                {step}
              </li>
            ))}
          </ol>
        </div>
      )}

      <div className="bg-gray-900 border border-gray-700 rounded-lg overflow-hidden">
        <div className="flex items-center justify-between px-4 py-2 bg-gray-800 border-b border-gray-700">
          <button
            className="text-xs text-gray-400 font-medium hover:text-gray-200 transition-colors"
            onClick={() => setShowCode(!showCode)}
          >
            {showCode ? '▼' : '▶'} コードを{showCode ? '隠す' : '表示'}
          </button>
          <div className="flex items-center gap-2">
            <button
              className="px-3 py-1 text-xs bg-gray-700 hover:bg-gray-600 text-gray-200 rounded transition-colors"
              onClick={handleCopy}
            >
              {copied ? 'コピー済み' : 'コピー'}
            </button>
            <button
              className="px-3 py-1 text-xs bg-green-700 hover:bg-green-600 text-white rounded transition-colors disabled:opacity-50 disabled:cursor-not-allowed flex items-center gap-1"
              onClick={handleExecute}
              disabled={executing}
            >
              {executing ? (
                <>
                  <span
                    data-testid="execute-spinner"
                    className="inline-block w-3 h-3 border border-white border-t-transparent rounded-full animate-spin"
                  />
                  実行中
                </>
              ) : (
                '実行'
              )}
            </button>
          </div>
        </div>
        {showCode && (
          <pre className="p-4 overflow-x-auto text-sm text-green-300 font-mono leading-relaxed">
            <code>{response.python_code}</code>
          </pre>
        )}
      </div>

      {executeError && (
        <div className="bg-red-950 border border-red-800 text-red-300 rounded-lg px-4 py-3 text-sm">
          {executeError}
        </div>
      )}

      {executeResponse && (
        <div className="bg-gray-800 border border-gray-700 rounded-lg p-4 space-y-3">
          <div className="flex items-center justify-between">
            <h2 className="text-sm font-semibold text-gray-400 uppercase tracking-wider">
              実行結果
            </h2>
            <div className="flex items-center gap-3">
              <span className="text-xs text-gray-500">{executeResponse.elapsed_ms}ms</span>
              {executeResponse.success ? (
                <span className="px-2 py-0.5 text-xs font-medium bg-green-900 text-green-300 rounded">
                  成功
                </span>
              ) : (
                <span className="px-2 py-0.5 text-xs font-medium bg-red-900 text-red-300 rounded">
                  エラー
                </span>
              )}
            </div>
          </div>

          {executeResponse.stdout && (
            <div>
              <p className="text-xs text-gray-500 mb-1">stdout</p>
              <pre data-testid="exec-stdout" className="bg-gray-900 rounded p-3 text-sm text-green-300 font-mono overflow-x-auto">
                {executeResponse.stdout}
              </pre>
            </div>
          )}

          {executeResponse.stderr && (
            <div>
              <p className="text-xs text-gray-500 mb-1">stderr</p>
              <pre className="bg-gray-900 rounded p-3 text-sm text-red-400 font-mono overflow-x-auto">
                {executeResponse.stderr}
              </pre>
            </div>
          )}

          {executeResponse.success && (
            <div className="space-y-3">
              <button
                className="px-4 py-2.5 text-sm bg-purple-700 hover:bg-purple-600 text-white rounded-lg transition-colors flex items-center gap-2 font-medium"
                onClick={handleDownloadTool}
              >
                <span>&#128230;</span>
                ツールとしてダウンロード
              </button>
              <p className="text-xs text-gray-500">
                ダウンロードしたzipを展開 → run.bat をダブルクリック or Excelをドラッグ＆ドロップ
              </p>
            </div>
          )}

          {executeResponse.output_files.length > 0 && (
            <div>
              <p className="text-xs text-gray-500 mb-2">出力ファイル</p>
              <ul className="space-y-2">
                {executeResponse.output_files.map((filePath) => {
                  const fileName = filePath.split('/').pop() || filePath
                  return (
                    <li key={filePath}>
                      <a
                        href={`/api/download/${filePath}`}
                        download={fileName}
                        className="inline-flex items-center gap-2 px-3 py-1.5 text-sm bg-blue-900 hover:bg-blue-800 text-blue-200 rounded transition-colors"
                      >
                        <span>&#8595;</span>
                        {fileName}
                      </a>
                    </li>
                  )
                })}
              </ul>
            </div>
          )}
        </div>
      )}

      {response.tips && (
        <div className="bg-yellow-950 border border-yellow-800 rounded-lg p-4">
          <h2 className="text-sm font-semibold text-yellow-400 mb-1">ヒント</h2>
          <p className="text-yellow-200 text-sm">{response.tips}</p>
        </div>
      )}
    </div>
  )
}
