/**
 * Build a GUI-enabled standalone Python script.
 * - Double-click: opens file picker dialog
 * - Drag & drop onto .bat: passes file as argument
 * - CLI: python tool.py --input file.xlsx
 */
export function buildToolScript(code: string, summary: string): string {
  const safeSummary = summary.replace(/\\/g, '\\\\').replace(/"/g, '\\"')

  return `#!/usr/bin/env python3
"""${safeSummary}

使い方:
    1. ダブルクリック → ファイル選択ダイアログが開きます
    2. ドラッグ＆ドロップ → 同梱の run.bat にExcelをドロップ
    3. コマンドライン → python tool.py --input ファイル.xlsx --output 出力先

Generated by ToolBilder
"""

import argparse
import os
import sys
import tkinter as tk
from tkinter import filedialog, messagebox

def _select_file_gui():
    """GUIでファイル選択ダイアログを表示"""
    root = tk.Tk()
    root.withdraw()
    root.attributes("-topmost", True)
    file_path = filedialog.askopenfilename(
        title="処理するExcelファイルを選択してください",
        filetypes=[("Excel files", "*.xlsx *.xls *.csv"), ("All files", "*.*")],
    )
    root.destroy()
    return file_path

def _show_result(message, is_error=False):
    """処理結果をダイアログで表示"""
    root = tk.Tk()
    root.withdraw()
    root.attributes("-topmost", True)
    if is_error:
        messagebox.showerror("エラー", message)
    else:
        messagebox.showinfo("完了", message)
    root.destroy()

def _setup():
    parser = argparse.ArgumentParser(description="${safeSummary}")
    parser.add_argument("--input", "-i", help="入力Excelファイルのパス")
    parser.add_argument("--output", "-o", help="出力ディレクトリ")
    parser.add_argument("file", nargs="?", help="入力ファイル（ドラッグ＆ドロップ用）")
    args = parser.parse_args()

    # 優先順位: --input > 位置引数 > GUIダイアログ
    input_file = args.input or args.file
    if not input_file:
        input_file = _select_file_gui()
    if not input_file:
        print("ファイルが選択されませんでした。")
        sys.exit(1)

    # 出力先: --output > 入力ファイルと同じディレクトリ
    output_dir = args.output or os.path.dirname(os.path.abspath(input_file))

    os.environ["INPUT_FILE"] = os.path.abspath(input_file)
    os.environ["OUTPUT_DIR"] = output_dir
    return input_file, output_dir

_input_file, _output_dir = _setup()

# ============================================================
# ここから生成されたコード
# ============================================================

${code}
`
}

export function buildBatFile(): string {
  return `@echo off
setlocal

set "TOOL_DIR=%~dp0"

where uv >nul 2>&1
if errorlevel 1 (
    echo [Setup] Installing uv ...
    powershell -ExecutionPolicy ByPass -Command "irm https://astral.sh/uv/install.ps1 | iex"
    set "PATH=%USERPROFILE%\\.local\\bin;%PATH%"
)

if not exist "%TOOL_DIR%.venv" (
    echo [Setup] Creating environment ...
    uv venv "%TOOL_DIR%.venv" --quiet
    echo [Setup] Installing dependencies ...
    uv pip install --python "%TOOL_DIR%.venv\\Scripts\\python.exe" pandas openpyxl --quiet
    echo [Setup] Ready.
    echo.
)

if "%~1"=="" (
    uv run --python "%TOOL_DIR%.venv\\Scripts\\python.exe" "%TOOL_DIR%tool.py"
) else (
    uv run --python "%TOOL_DIR%.venv\\Scripts\\python.exe" "%TOOL_DIR%tool.py" --input "%~1"
)

if errorlevel 1 (
    echo.
    echo Error occurred.
)
pause
`
}

export function buildReadme(summary: string, steps: string[]): string {
  const stepList = steps.map((s, i) => `${i + 1}. ${s}`).join('\n')
  return `# ツール説明

${summary}

## 使い方

### 方法1: ダブルクリック（一番簡単）
1. run.bat をダブルクリック
2. ファイル選択ダイアログが表示されます
3. 処理するExcelファイルを選択
4. 処理結果が同じフォルダに出力されます

### 方法2: ドラッグ＆ドロップ
1. 処理するExcelファイルを run.bat にドラッグ＆ドロップ
2. 処理結果が同じフォルダに出力されます

## 処理内容
${stepList}

## 必要な環境
- Python 3.10以上
- pip install pandas openpyxl

Generated by ToolBilder
`
}
